### ISSUE TITLE
Missing HTTP request attributes in Kafka messages

### ISSUE THREAD

**Issue by andrademf** [lsevero/franz#6]
In order to fully recovery the HTTP request the message added to the Kafka topic should contains more data from the request, such the **header** and **route**. 

Use cases for those could be some:
- authorization via header values in future procedures;
- query request with values in the route, e.g: ```GET /users/{document_number}/```, as will not be possible to create a serape topic for each user

**Comment by lsevero** [comment]
Good idea, I'll do it.

**Comment by lsevero** [comment]
Done in v1.3.0
